on:
    push:
    pull_request:

name: Lint

jobs:
    doctor-rst:
        name: DOCtor-RST

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: "Lint files"
              uses: docker://oskarstark/doctor-rst
              with:
                  args: --short
